name: CI

on:
  push:
    branches: [ feature/dev ]
    tags:
      - 'v*.*.*'  # Triggers on version tags like v0.1.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          pip install build
          python -m build
      
      - name: Check built distributions
        run: |
          pip install twine
          twine check dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          pip install twine
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Install the package (optional)
        run: |
          pip install dist/*.whl
